### ISSUE TITLE
非常棒，如果能把音乐库也加进去就好了！

### ISSUE THREAD

**Issue by EricEdelstein** [sqkkyzx/plex_localization_zhcn#1]
现在这个版本电影库和电视剧包括视频库都可以进行优化了，但是唯独不支持音乐库，如果能支持音乐库就好了！

另外有些分类标签我感觉好像没有识别出来？执行过以后还是剩了一些英文标签没有变成中文，我就手动改了一些。还有那个标签的中文名是不是自己手动改改也可以啊？比如我把那个“体育”改成“运动”了，应该也不影响吧，如果想自己增加一些分类可以按照格式添加吗？比如我库里还有迷你剧这个分类，可以不可以自己添加一个对应关系呢？

**Comment by sqkkyzx** [comment]
分类标签可以自行按照格式设置英文和中文的键值对。即使你把”体育“改成”强壮的身体“也没有关系

**Comment by sqkkyzx** [comment]
> 

这个问题我有注意到，主要是TV的标签好像不完全是写在一个地方的。音乐库的元数据好像和电影库也不是在同一个位置，我大概有个思路，但是最近实在是太忙了没空弄

**Comment by sqkkyzx** [comment]
> > 我过几天空闲了看一下吧
> 
> 另外目前的拼音排序功能对合集标题不起作用，有没有办法支持合集标题拼音排序和搜索啊？

合集应该是很好加进去拼音排序。

**Comment by sqkkyzx** [comment]
> > 我过几天空闲了看一下吧
> 
> 大佬，我发觉你的版本类型汉化似乎有点问题，执行完以后还是有很多类型标签没有汉化成功（这些标签在脚本里写了对应关系），我使用[timmy0209](https://github.com/timmy0209)的[plex-chinese-genre](https://github.com/timmy0209/plex-chinese-genre)这个脚本就全部汉化成功了，但是他这个脚本只能汉化电影库的，不能汉化电视剧库，大佬能不能检查一下你的脚本，类型汉化是不是有BUG啊？我不懂代码，不会自己改。

搞定收工。全部修复。音乐、剧集都可以。
