### ISSUE TITLE
类型标签是否可以增加自动锁定的功能？

### ISSUE THREAD

**Issue by x1ao4** [sqkkyzx/plex_localization_zhcn#2]
首先感谢大佬百忙之中抽时间更新了脚本，新的脚本一切功能正常，非常棒！

不过有几个点想探讨一下。

第一是，现在「标题排序」和「艺术家排序」修改为拼音后会自动锁定，刷新元数据就不受影响了。那「类型标签」在汉化之后是否也可以自动锁定呢？能否用同样的方式使类型标签在汉化之后也自动锁定？

第二是，音乐媒体库中有一个「类型/流派（Genre）」和一个「风格（Styles）」，目前汉化的是「类型/流派（Genre）」标签，有没有可能给「风格（Styles）」也增加同样的汉化功能？然后也同时支持在汉化后自动锁定？

第三是，有没有可能为「专辑排序」也增加一个改为拼音首字母并自动锁定的功能呢？

最后再次感谢一下大佬，脚本很实用。

**Comment by sqkkyzx** [comment]
类型标签锁定是可以实现的。 styles应该也可以做汉化。改天我抽空加一下吧。

**Comment by Wrandz** [comment]
> > 
> 
> 感谢更新，完美！

看了你的b站文章才发现这的，感谢你！
