### ISSUE TITLE
电影系列中电影不显示

### ISSUE THREAD

**Issue by zg601x** [sqkkyzx/plex_localization_zhcn#3]
作者大佬您好，这两天刚用上您这个脚本，使用中遇到一个小问题：

当plex“电影”开启显示系列功能后，并且选择”隐藏合集中的项目“后，电影“资料库”列表中就不能通过首字母排序来检索系列中的影片了；

而且右边检索按钮[A-Z]最下面会出现该系列中文名称的第一个中文字；当我编辑这些电影系列来查看“标题/排序”的时候，发现“排序”这栏并没有被转换成全拼音；

如果我想正常通过首字母排序来检索这些系列中的影片，就必须禁用“合集”显示功能

**Comment by sqkkyzx** [comment]
预期月底修

**Comment by zg601x** [comment]
期待ing

**Comment by sqkkyzx** [comment]
搞完。更新一大堆

**Comment by zg601x** [comment]
谢谢大佬！！

**Comment by zg601x** [comment]
不过第三方库有支持自动查找和选择已有的库，也修复了合集问题了

**Comment by zg601x** [comment]
> 不过第三方库有支持自动查找和选择已有的库，也修复了合集问题了

不过开发者能更新肯定是最好的，毕竟代码也熟悉

**Comment by sqkkyzx** [comment]
自动查找和选择已有的库，参考 readme 里面 ‘’非交互式运行“ 的 ”特殊用例“。
可以直接一次性便利所有库。

**Comment by zg601x** [comment]
当时回复第一句话时，确实没有看到，后面才看到的
