### ISSUE TITLE
音乐库的单曲排序似乎不能生效

### ISSUE THREAD

**Issue by zph308** [sqkkyzx/plex_localization_zhcn#4]
按照脚本运行后使用plexamp，歌曲排序并没有变化。
看了一下plex音乐库中的单曲好像并不支持单独设置标题排序设置项

**Comment by zph308** [comment]
已成功连接到服务器Tower
0> 电影
1> 音乐
请选择库：1

1> 电影
2> 节目
8> 艺术家
9> 专辑
10> 单曲
请选择要操作的类型：10
共计773个媒体
选择艺术家和专辑都有效果，但是单曲不行

**Comment by sqkkyzx** [comment]
收到，我看看情况

**Comment by sqkkyzx** [comment]
单曲确实不支持设置标题排序，PLEX不支持该设置项，该问题目前没什么解决办法。
