### ISSUE TITLE
不在标准流派范围内的标签是否可以顺便删除掉？

### ISSUE THREAD

**Issue by Wrandz** [sqkkyzx/plex_localization_zhcn#5]
### 使用了脚本将流派标签都改成应为后发现还是有一个英文的
![1](https://github.com/sqkkyzx/plex_localization_zhcn/assets/70056470/4a47bdc0-444a-419c-b6ec-84332f1cd860)
### 看了一下这属于一部电影叫《平民窟的百万富翁》，
![2](https://github.com/sqkkyzx/plex_localization_zhcn/assets/70056470/3fdfe6fe-f946-47f0-be7d-55181dc12048)
### 这个标签应该指的是印度电影的意思，但是我的库中也有其他的印度电影，而且感觉这个标签并不属于正常的流派类型（如动作、科幻这种）。
![3](https://github.com/sqkkyzx/plex_localization_zhcn/assets/70056470/4c81f8e3-60fd-43d5-a1d5-a7a36e2add53)

**Comment by sqkkyzx** [comment]
可以实现功能，但可能不太适合完全自动化，会带来误删的可能。一两部的话建议手动删除吧。
